apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-fl5d
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0017-tenant/tkrw-pr712-0075-0017-app/devfile-sample-fl5d@sha256:c90929da015cbfb393838ee135735c2dbdfbfc6c629421a7444f006198e285f6
        name: my-nodejs
        resources: {}
status: {}
